spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/Ticket
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: Ticket-App
      principle-attribute: preferred_username

keycloak:
  domain: http://localhost:8088
  realm: Ticket
  adminClientId: admin-cli
  adminClientSecret: yVxzziRwWkyDmkTFyeVgnwRkKYWJuhIW
  client: Ticket-App
  urls:
    auth: http://localhost:8088