server:
  port: 8080
spring:
  application:
    name: APIGateWay
  cloud:
    gateway:
     routes:
       - id: auth
         uri: lb://AUTH
         predicates:
           - Path=/auth/**

       - id: event
         uri: lb://EVENT
         predicates:
           - Path=/events/**


       - id: eventticket
         uri: lb://EVENTTICKET
         predicates:
           - Path=/ticket/**

        

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/Ticket
          jwk-set-uri: http://localhost:8088/realms/Ticket/protocol/openid-connect/certs
          audience: account
eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
