server:
  port: 8081

spring:
  application:
    name: event
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/Event
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
#  zipkin:
#    base-url: http://localhost:9411
#  rabbitmq:
#    addresses: localhost:5672
#eureka:
#  client:
#    server-url:
#      defaultZone: http://localhost:8761/eureka/
#    enabled: false